apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flipstarter-eatbch-ingress
  namespace: default
  annotations:
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - flipstarter2.eatbch.org
    secretName: flipstarter-eatbch-tls
  defaultBackend:
    service:
      name: flipstarter-eatbch
      port:
        number: 350
  rules:
  - host: flipstarter2.eatbch.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: flipstarter-eatbch
            port:
              number: 350
