apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flipstarter-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - flipstarter.eatbch.org
    secretName: flipstarter-tls
  defaultBackend:
    service:
      name: flipstarter
      port:
        number: 300
  rules:
  - host: flipstarter.eatbch.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: flipstarter
            port:
              number: 300
