apiVersion: v1
kind: Service
metadata:
  name: flipstarter-globalbitcoin
  namespace: default
spec:
  ports:
    - port: 305
      targetPort: 3000
  selector:
    service: flipstarter-globalbitcoin
  type: NodePort
