apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flipstarter-globalbitcoin-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - flipstarter.globalbitcoin.cash
      secretName: flipstarter-globalbitcoin-tls
  defaultBackend:
    service:
      name: flipstarter-globalbitcoin
      port:
        number: 305
  rules:
    - host: flipstarter.globalbitcoin.cash
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: flipstarter-globalbitcoin
                port:
                  number: 305
