apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flipstarter-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - flipstarter.eatbch.org
    secretName: flipstarter-tls
  backend:
    serviceName: flipstarter
    servicePort: 300
  rules:
  - host: flipstarter.eatbch.org
    http:
      paths:
      - path: /
        backend:
          serviceName: flipstarter
          servicePort: 300
